dataset:
  train:
    target: dataset.codeformer_test.CodeformerDataset
    params:
      # training file list path
      gt_file:
      grad_file: 
      lq_file: 
      # file_backend_cfg:
        # target: dataset.file_backend.HardDiskBackend
      # out_size: 512
      crop_type: center
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]

  val:
    target: dataset.codeformer_test.CodeformerDataset
    params:
      gt_file:
      grad_file: 
      lq_file: 
      crop_type: center
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]

train:
  sd_path: 
  exp_dir: 
  batch_size: 1
  num_workers: 1
  train_steps: 600000
  log_every: 50
  ckpt_every: 500
  image_every: 500
  val_every: 500
  resume:
  cond_resume:
  gard_resume: 
  
test:
  guidance:
    or_not: true
    g_loss: 'ncc'
    g_scale: 1
    g_start: 151
    g_stop: -1
    g_space: rgb
    g_repeat: 1
