dataset:
  train:
    target: dataset.codeformer_vae_new.CodeformerDataset
    params:
      gt_file: /data1/baihy/denoise/data/ANDI/Gt_fsl_norm/train_gradients
      lq_file: /data1/baihy/results/ADNI/stage1/train_combined
      crop_type: center
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]

  val:
    target: dataset.codeformer_vae_new.CodeformerDataset
    params:
      gt_file: /data1/baihy/denoise/data/ANDI/Gt_fsl_norm/val_gradients
      lq_file: /data1/baihy/results/ADNI/stage1/val_combined
      crop_type: center
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]

train:
  exp_dir: /data1/baihy/denoise/experiment
  learning_rate: 1e-5
  batch_size: 3
  num_workers: 1
  train_steps: 60000
  log_every: 50
  ckpt_every: 500
  image_every: 100
  val_every: 500
  resume: ~
  
