model:
  swinir:
    target: model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 1
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 4
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 4

dataset:
  train:
    target: dataset.codeformer.CodeformerDataset
    params:
      gt_file: /data1/baihy/denoise/data/ANDI/Gt_Slice/train
      lq_file: /data1/baihy/denoise/data/ANDI/Degrade_Slice/train
      file_backend_cfg:
        target: dataset.file_backend.HardDiskBackend
      crop_type: none
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]
  val:
    target: dataset.codeformer.CodeformerDataset
    params:
      gt_file: /data1/baihy/denoise/data/ANDI/Gt_Slice/val
      lq_file: /data1/baihy/denoise/data/ANDI/Degrade_Slice/val
      file_backend_cfg:
        target: dataset.file_backend.HardDiskBackend
      crop_type: none
      blur_kernel_size: 41
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [0.1, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]

train:
  # experiment directory path
  exp_dir: stage1
  learning_rate: 5e-5
  # total batch size
  batch_size: 96
  num_workers: 8
  train_steps: 150000
  log_every: 50
  ckpt_every: 500
  image_every: 50
  val_every: 500
  resume: ~